version: '3.3'

services:
  # WORDPRESS IMAGE
  wp:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - ${IP}:80:80
    restart: always
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
      - ./app/plugins:/var/www/html/wp-content/plugins
      - ./app/themes/custom:/var/www/html/wp-content/themes/custom
      - ./app/uploads:/var/www/html/wp-content/uploads
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: '${DB_ROOT_PASSWORD}'
      WORDPRESS_DB_NAME: '${DB_NAME}'

  # WP-CLI
  wpcli:
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    depends_on:
      - db
      - wp

  # DATABASE
  db:
    image: mysql:latest
    ports:
      - ${IP}:3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'

  # PHP MY ADMIN
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    ports:
      - ${IP}:8080:80
    links:
      - db:db

volumes:
  db_data: {}
